CREATE PROCEDURE [tst].[reset_states]
	
AS
	INSERT INTO [tst].[states] (name,abbrev) VALUES ('Alabama', 'AL');
	INSERT INTO [tst].[states] (name,abbrev) VALUES ('Alaska', 'AK');
	INSERT INTO [tst].[states] (name,abbrev) VALUES ('American Samoa', 'AS');
	INSERT INTO [tst].[states] (name,abbrev) VALUES ('Arizona', 'AZ');
	INSERT INTO [tst].[states] (name,abbrev) VALUES ('Arkansas', 'AR');
	INSERT INTO [tst].[states] (name,abbrev) VALUES ('California', 'CA');
	INSERT INTO [tst].[states] (name,abbrev) VALUES ('Colorado', 'CO');
	INSERT INTO [tst].[states] (name,abbrev) VALUES ('Connecticut', 'CT');
	INSERT INTO [tst].[states] (name,abbrev) VALUES ('Delaware', 'DE');
	INSERT INTO [tst].[states] (name,abbrev) VALUES ('District of Columbia', 'DC');
	INSERT INTO [tst].[states] (name,abbrev) VALUES ('Federated States of Micronesia', 'FM');
	INSERT INTO [tst].[states] (name,abbrev) VALUES ('Florida', 'FL');
	INSERT INTO [tst].[states] (name,abbrev) VALUES ('Georgia', 'GA');
	INSERT INTO [tst].[states] (name,abbrev) VALUES ('Guam', 'GU');
	INSERT INTO [tst].[states] (name,abbrev) VALUES ('Hawaii', 'HI');
	INSERT INTO [tst].[states] (name,abbrev) VALUES ('Idaho', 'ID');
	INSERT INTO [tst].[states] (name,abbrev) VALUES ('Illinois', 'IL');
	INSERT INTO [tst].[states] (name,abbrev) VALUES ('Indiana', 'IN');
	INSERT INTO [tst].[states] (name,abbrev) VALUES ('Iowa', 'IA');
	INSERT INTO [tst].[states] (name,abbrev) VALUES ('Kansas', 'KS');
	INSERT INTO [tst].[states] (name,abbrev) VALUES ('Kentucky', 'KY');
	INSERT INTO [tst].[states] (name,abbrev) VALUES ('Louisiana', 'LA');
	INSERT INTO [tst].[states] (name,abbrev) VALUES ('Maine', 'ME');
	INSERT INTO [tst].[states] (name,abbrev) VALUES ('Marshall Islands', 'MH');
	INSERT INTO [tst].[states] (name,abbrev) VALUES ('Maryland', 'MD');
	INSERT INTO [tst].[states] (name,abbrev) VALUES ('Massachusetts', 'MA');
	INSERT INTO [tst].[states] (name,abbrev) VALUES ('Michigan', 'MI');
	INSERT INTO [tst].[states] (name,abbrev) VALUES ('Minnesota', 'MN');
	INSERT INTO [tst].[states] (name,abbrev) VALUES ('Mississippi', 'MS');
	INSERT INTO [tst].[states] (name,abbrev) VALUES ('Missouri', 'MO');
	INSERT INTO [tst].[states] (name,abbrev) VALUES ('Montana', 'MT');
	INSERT INTO [tst].[states] (name,abbrev) VALUES ('Nebraska', 'NE');
	INSERT INTO [tst].[states] (name,abbrev) VALUES ('Nevada', 'NV');
	INSERT INTO [tst].[states] (name,abbrev) VALUES ('New Hampshire', 'NH');
	INSERT INTO [tst].[states] (name,abbrev) VALUES ('New Jersey', 'NJ');
	INSERT INTO [tst].[states] (name,abbrev) VALUES ('New Mexico', 'NM');
	INSERT INTO [tst].[states] (name,abbrev) VALUES ('New York', 'NY');
	INSERT INTO [tst].[states] (name,abbrev) VALUES ('North Carolina', 'NC');
	INSERT INTO [tst].[states] (name,abbrev) VALUES ('North Dakota', 'ND');
	INSERT INTO [tst].[states] (name,abbrev) VALUES ('Northern Mariana Islands', 'MP');
	INSERT INTO [tst].[states] (name,abbrev) VALUES ('Ohio', 'OH');
	INSERT INTO [tst].[states] (name,abbrev) VALUES ('Oklahoma', 'OK');
	INSERT INTO [tst].[states] (name,abbrev) VALUES ('Oregon', 'OR');
	INSERT INTO [tst].[states] (name,abbrev) VALUES ('Palau', 'PW');
	INSERT INTO [tst].[states] (name,abbrev) VALUES ('Pennsylvania', 'PA');
	INSERT INTO [tst].[states] (name,abbrev) VALUES ('Puerto Rico', 'PR');
	INSERT INTO [tst].[states] (name,abbrev) VALUES ('Rhode Island', 'RI');
	INSERT INTO [tst].[states] (name,abbrev) VALUES ('South Carolina', 'SC');
	INSERT INTO [tst].[states] (name,abbrev) VALUES ('South Dakota', 'SD');
	INSERT INTO [tst].[states] (name,abbrev) VALUES ('Tennessee', 'TN');
	INSERT INTO [tst].[states] (name,abbrev) VALUES ('Texas', 'TX');
	INSERT INTO [tst].[states] (name,abbrev) VALUES ('Utah', 'UT');
	INSERT INTO [tst].[states] (name,abbrev) VALUES ('Vermont', 'VT');
	INSERT INTO [tst].[states] (name,abbrev) VALUES ('Virgin Islands', 'VI');
	INSERT INTO [tst].[states] (name,abbrev) VALUES ('Virginia', 'VA');
	INSERT INTO [tst].[states] (name,abbrev) VALUES ('Washington', 'WA');
	INSERT INTO [tst].[states] (name,abbrev) VALUES ('West Virginia', 'WV');
	INSERT INTO [tst].[states] (name,abbrev) VALUES ('Wisconsin', 'WI');
	INSERT INTO [tst].[states] (name,abbrev) VALUES ('Wyoming', 'WY');
	INSERT INTO [tst].[states] (name,abbrev) VALUES ('Armed Forces Africa', 'AE');
	INSERT INTO [tst].[states] (name,abbrev) VALUES ('Armed Forces Americas (except Canada)', 'AA');
	INSERT INTO [tst].[states] (name,abbrev) VALUES ('Armed Forces Canada', 'AE');
	INSERT INTO [tst].[states] (name,abbrev) VALUES ('Armed Forces Europe', 'AE');
	INSERT INTO [tst].[states] (name,abbrev) VALUES ('Armed Forces Middle East', 'AE');
	INSERT INTO [tst].[states] (name,abbrev) VALUES ('Armed Forces Pacific', 'AP');
RETURN 0
