EXEC [WDS].[add_parameter_example_value] 'TestingOnly', 'DimDatesJson', 'Monday', 'Day_Name', 'Monday'
EXEC [WDS].[add_parameter_example_value] 'TestingOnly', 'DimDatesJson', 'Tuesday', 'Day_Name', 'Tuesday'
EXEC [WDS].[add_parameter_example_value] 'TestingOnly', 'DimDatesJson', 'Wednesday', 'Day_Name', 'Wednesday'
EXEC [WDS].[add_parameter_example_value] 'TestingOnly', 'DimDatesJson', 'Thursday', 'Day_Name', 'Thursday'
EXEC [WDS].[add_parameter_example_value] 'TestingOnly', 'DimDatesJson', 'Friday', 'Day_Name', 'Friday'
EXEC [WDS].[add_parameter_example_value] 'TestingOnly', 'DimDatesJson', 'Saturday', 'Day_Name', 'Saturday'
EXEC [WDS].[add_parameter_example_value] 'TestingOnly', 'DimDatesJson', 'Sunday', 'Day_Name', 'Sunday'

EXEC [WDS].[add_parameter_example_value] 'TestingOnly', 'DimDatesXml', 'Monday', 'Day_Name', 'Monday'
EXEC [WDS].[add_parameter_example_value] 'TestingOnly', 'DimDatesXml', 'Tuesday', 'Day_Name', 'Tuesday'
EXEC [WDS].[add_parameter_example_value] 'TestingOnly', 'DimDatesXml', 'Wednesday', 'Day_Name', 'Wednesday'
EXEC [WDS].[add_parameter_example_value] 'TestingOnly', 'DimDatesXml', 'Thursday', 'Day_Name', 'Thursday'
EXEC [WDS].[add_parameter_example_value] 'TestingOnly', 'DimDatesXml', 'Friday', 'Day_Name', 'Friday'
EXEC [WDS].[add_parameter_example_value] 'TestingOnly', 'DimDatesXml', 'Saturday', 'Day_Name', 'Saturday'
EXEC [WDS].[add_parameter_example_value] 'TestingOnly', 'DimDatesXml', 'Sunday', 'Day_Name', 'Sunday'

EXEC [WDS].[add_parameter_example_value] 'TestingOnly', 'DimDatesCSV', 'Monday', 'Day_Name', 'Monday'
EXEC [WDS].[add_parameter_example_value] 'TestingOnly', 'DimDatesCSV', 'Tuesday', 'Day_Name', 'Tuesday'
EXEC [WDS].[add_parameter_example_value] 'TestingOnly', 'DimDatesCSV', 'Wednesday', 'Day_Name', 'Wednesday'
EXEC [WDS].[add_parameter_example_value] 'TestingOnly', 'DimDatesCSV', 'Thursday', 'Day_Name', 'Thursday'
EXEC [WDS].[add_parameter_example_value] 'TestingOnly', 'DimDatesCSV', 'Friday', 'Day_Name', 'Friday'
EXEC [WDS].[add_parameter_example_value] 'TestingOnly', 'DimDatesCSV', 'Saturday', 'Day_Name', 'Saturday'
EXEC [WDS].[add_parameter_example_value] 'TestingOnly', 'DimDatesCSV', 'Sunday', 'Day_Name', 'Sunday'

EXEC [WDS].[add_parameter_example_value] 'TestingOnly', 'EVehiclePopulation', 'SetA', 'numRows', '100'